### PR TITLE
update na_mean

### PR DESCRIPTION
**Pull request by trafficonese**
Include option for **harmonic** and **geometric** mean

Update Roxygen to 6.1.1, added Encoding to DESCRIPTION

I had to delete all non .cpp files in /src to be able to build it, thats why there are so many changes.

And unfortunately I was not able to check the package, as I am missing `R.rsp`, but the changes are not very drastic, so the tests should still pass.

### CODE REVIEW

**Comment by trafficonese** [comment]
I am not sure about the geometric method, as it might produce `Inf` values.

I just found out, by writing some tests:
```
x <- tsAirgap
mean(na_mean(x, option ="mean", meanmethod = "g"))
```
----------------------------------------


That's the geometric mean function right now:
`prod(data, na.rm = TRUE)^(1 / length(data))`

I'm not sure if the whole length should be taken or the length of all non-NA values, which would look like:
`prod(data, na.rm = TRUE)^(1 / length(data[!is.na(data)]))`

This will still result in `Inf` values, as the product will grow too big. We could normalize the data by dividing first with the maximum of all values and then multiplying it back.

This would look like:
`(prod(x/max(x, na.rm=T), na.rm = TRUE)^(1 / length(x[!is.na(x)]))) * max(x, na.rm=T)`
and so far I havent seen any `Inf` values with this approach.

Now the only question I have is whether to take the full length (1) or the reduced length without NA values (2).
1) `(prod(x/max(x, na.rm=T), na.rm = TRUE)^(1 / length(x))) * max(x, na.rm=T)`
2) `(prod(x/max(x, na.rm=T), na.rm = TRUE)^(1 / length(x[!is.na(x)]))) * max(x, na.rm=T)`

What would make more sense? I think option2 would, but as I am not a statistician, I would leave that decision to you ;)

**Comment by SteffenMoritz** [comment]
Woow, you are ultra fast :D I'll directly have a look tomorrow :)

**Comment by SteffenMoritz** [comment]
Sooo today I had time to think about it :)

**About "R.rsp":**
This is just an R package. You can install it just like any other package and it should work :)

**About "I'm not sure if the whole length should be taken or the length of all non-NA values":**
I think it should be "number of all non-NA values"

**About the syntax:**
What do you think of just adding these two as option ="harmonic" and option ="geometric"? Wouldn't that be easier to understand for users?
I thought it might be somehow confusing to have an additional parameter(meanmethod) that just works for a certain parameter configuration( option ="mean").

**Comment by SteffenMoritz** [comment]
**About the Inf issue:**
I tested now the version with prod(). You are right .. it failed already for pretty small time series.
What about: exp(mean(log(data)))  ?
Not my invention ;) , seen this somewhere and seems to work (but did not test it extensively)

*edit*
Just did another test on the rather large tsHeating series provided by the package, exp(mean(log(tsHeatingComplete))) - also worked for me in reasonable time and no Inf or something.

*edit2*
prod(tsHeatingComplete/max(tsHeatingComplete, na.rm=T), na.rm = TRUE)^(1 / length(tsHeatingComplete[!is.na(tsHeatingComplete)])) * max(tsHeatingComplete, na.rm=T)
[1] 0

On the long time series the prod() version might also suffer from too big numbers ... somehow the result was 0 for me. (but did just this one test - maybe just me doing something wrong)

**Comment by trafficonese** [comment]
Indeed, the normalization with the maxum value doesn't always work. 
So I think you're right, the following makes more sense.
`exp(mean(log(data), na.rm = T))`

If you mean adding them to the `option` argument, that would definitly also be possible and it wouldnt need another argument.

I now have `R.rsp` installed, but I'm still missing a Latex on this computer, so I wasnt able to run the full checks.

**Comment by SteffenMoritz** [comment]
Perfect, looks really good now :)

**Comment by SteffenMoritz** [comment]
Would you mind removing the .o .so .dll files from the pull request? xD
Wasn't able to merge - as I added this files to .gitignore (to prevent multiple re-uploads)
Maybe I'll have to take a closer look on how to use git .. I always have issues merging conflicting pull requests ;)

Oh what I also realized, we should probably add a a stop condition to harmonic and geometric mean.

"datasets with 0’s cannot be used with the geometric or harmonic means, 
& datasets with negative numbers also rule out the geometric mean"

Think it these means don't work for these conditions.

Should we add message like:
(if has a 0 or has a negative number)
stop("geometric mean is not definied for data containing 0's or negative numbers ... . Your data contains these - use another methods like...instead)
?

**Comment by trafficonese** [comment]
Should there be a stop-error or just a warning that the results will not be reasonable, as it actually doesnt throw an error?

**Comment by SteffenMoritz** [comment]
Good point about the warning.
Let's check, how reasonable the harmonic and geometric mean values with negative input are actually.
Then we'll decide.

**Comment by SteffenMoritz** [comment]
Ok, did some tests:

> xx <- c(-4,-5,-7,-8,-4,-7,-4,-9,-3)
> na_mean(xx, option ="mean")
[1] -4 -5 -7 -8 -4 -7 -4 -9 -3
> xx <- c(-4,-5,-7,-8,-4,-7,-4,-9,-3, NA)
> na_mean(xx, option ="mean")
 [1] -4.000000 -5.000000 -7.000000 -8.000000 -4.000000 -7.000000 -4.000000 -9.000000 -3.000000 -5.666667
> na_mean(xx, option ="harmonic")
 [1] -4.000000 -5.000000 -7.000000 -8.000000 -4.000000 -7.000000 -4.000000 -9.000000 -3.000000 -4.985711
> na_mean(xx, option ="geometric")
 [1]  -4  -5  -7  -8  -4  -7  -4  -9  -3 NaN
Warnmeldung:
In log(data) : NaNs wurden erzeugt
> ccc <- c(0,0,0,0,0,0,0,0,0,NA)
> na_mean(cc, option ="geometric")
Fehler in na_mean(cc, option = "geometric") : Objekt 'cc' nicht gefunden
> na_mean(ccc, option ="geometric")
 [1] 0 0 0 0 0 0 0 0 0 0
> na_mean(ccc, option ="harmonic")
 [1] 0 0 0 0 0 0 0 0 0 0
> xx <- c(-4,-5,-7,-8,-4,-7,-4,-9,1, NA)
> na_mean(xx, option ="harmonic")
 [1]  -4.00000  -5.00000  -7.00000  -8.00000  -4.00000  -7.00000  -4.00000  -9.00000   1.00000 -19.07485
> na_mean(xx, option ="geometric")
 [1] -4 -5 -7 -8 -4 -7 -4 -9  1  1
Warnmeldung:
In log(data) : NaNs wurden erzeugt
> vvv <- c(1,2,4,0,0,3,NA)
> na_mean(vvv, option ="geometric")
[1] 1 2 4 0 0 3 0
> na_mean(vvv, option ="harmonic")
[1] 1 2 4 0 0 3 0
> bbb <- c(-4,-5,-6,-7,-9,NA)
> na_mean(bbb, option ="harmonic")
[1] -4.000000 -5.000000 -6.000000 -7.000000 -9.000000 -5.742935
> na_mean(bbb, option ="geometric")
[1]  -4  -5  -6  -7  -9 NaN
Warnmeldung:
In log(data) : NaNs wurden erzeugt

**Comment by SteffenMoritz** [comment]
My results:

1. As soos as there is a 0 in the input data, gm and hm are always 0  
-> 0 in the input data must be prohibited via stop()

2. If input values are all positive numbers  and != 0 
Everything works always fine.

3. Mixed sign input data gives strange results:
xx <- c(-4,-5,-7,-8,-4,-7,-4,-9,1, NA)
na_mean(xx, option ="harmonic")
[1] -4.00000 -5.00000 -7.00000 -8.00000 -4.00000 -7.00000 -4.00000 -9.00000 1.00000 -19.07485
na_mean(xx, option ="geometric")
[1] -4 -5 -7 -8 -4 -7 -4 -9 1 1
-> So we have to make sure, input is either all positive or all negative (and no 0's)

4. Harmonic mean with all negative numbers seems to work fine
bbb <- c(-4,-5,-6,-7,-9,NA)
> na_mean(bbb, option ="harmonic")
[1] -4.000000 -5.000000 -6.000000 -7.000000 -9.000000 -5.742935

5. Geometric mean with all negative numbers seems to have problems
bbb <- c(-4,-5,-6,-7,-9,NA)
> na_mean(bbb, option ="geometric")
[1]  -4  -5  -6  -7  -9 NaN
But we probably could mitigate the last thing - if we change signs into positive first (*-1) calculate the gm and then take the result (*-1) again

**Comment by trafficonese** [comment]
Also jetzt ist ein stop() drin, wenn 0 oder Negativwerte vorkommen für geometric/harmonic mean.
Natürlich können wir das aber noch anpassen.

**Comment by SteffenMoritz** [comment]
Eben nochmal drüber nachgedacht und etwas getestet.
Ja, das lassen wir jetzt so :)

Voll, gut, kaum ne Woche her, dass das die 3.0 Version herauskam, schon
haben wir das nächste Feature :)
Danke dir.

Am Do., 11. Juli 2019 um 15:04 Uhr schrieb trafficonese <
notifications@github.com>:

**Pull request merged**
