### PR TITLE
ggplot2 plots / deprecate old functions with .

### PR DESCRIPTION
**Pull request by YsoSirius**
This PR needs some intensive reviewing, especially for the documentation and the arguments. Also, the "..." argument might be placed differently/better. 

In all plotting code I found this line:
` if (!is.ts(data)) {data <- as.vector(data)}`
I think the "!" is too much here, as you only convert to vector when its Not a timeseries. Anyway, I think it works in any case, at least for the examples I tried.

Another thing, I didnt manage to align with the old functionality:
When using `plotNA.distributionBar` (or `plotNA_distributionBar,` the new version), and the last bar width should be different, they were aligned nicely with `barplot`, but with ggplot2 its a bit different.
See this example:
`plotNA_distributionBar(tsNH4, breaksize = 500)`

The last bar is aligned on the right and is further away from the other bars. I didnt find a fix for that, but my ggplot skills are also quite limited.. 

Unfortunately, I got a bit of a mess with my fork, as it is quite some commits behind and while trying to figure out what happened in `plotNA.gapsize`, I found the PR (#37) from @earowang, which made more sense and so I included it in this PR too.. I hope it doesnt end up in a complete merge chaos.

### CODE REVIEW

**Comment by SteffenMoritz** [comment]
Wow! I'm quite excited to try this out!!
I'll try to give some feedback tomorrow :)

Yeah you are right, we have to test tand fine-tune his intensively. 

By the way, did you see the new Wiki (?)
https://github.com/SteffenMoritz/imputeTS/wiki

As said there - the new revised plotting functions need not necessarily the same names.
Although having the same function names (just with _) is probably quite convenient.
Would be quite interesting to hear your opinion about this.

"Unfortunately, I got a bit of a mess with my fork" <- I always have the same problems xD

**Comment by trafficonese** [comment]
I just had a look at the wiki! +1

I think just replacing "." with "_" seems ok, except you want to have different names, but I think they're ok.
I will also write some tests for the new plotting functions, to get at least back to the old coverage.

One nice feature about the ggplots is that you can wrap it into `plotly::ggplotly()` and you will get an interactive chart, although the names/labels might have to be adapted.

**Comment by SteffenMoritz** [comment]
Just did a first test.
The plots look really nice now! :)

**Comment by SteffenMoritz** [comment]
I did some additional updates:

- some changes, because there were some check() errors

- added ggplot2:: before every function ggplot function call (it is somehow more code - but especially if you import multiple packages / or even packages who supply the same function - you later on know, which package the function you are calling is from - also useful if you are looking for unused imports)

- Some changes according to styleR + lintR (as mentioned in the wiki, especially styleR is useful and some suggestions by lintr are also worth following)

- Added you as -aut- to the package because you are doing so many cool things for the package 👍

**Comment by SteffenMoritz** [comment]
Ahh and I removed the suppressWarnings  - for me there were no warnings? Maybe I should ask why you put it there xD (not that it was actually needed)

I also now explicitly return (return(gg) ) for every function the gg plot object.

I still have to check if adapting this gg object works fine for the user.
(so that they can do something like plotNA.distribution(data) + ggtitle()...  )

So that they can enhance their plots. Guess adding something we did not specify yet seems easy...but I wonder what happens for things we already added somehow.

**Comment by trafficonese** [comment]
I think the `suppressWarnings` came from converting with `ggplotly()` but I'm not sure anymore. :)

Yes it wouldbe nice, if user could use the plot and add elements, so returning the plot seems reasonable.
There might be something to fix then, as I ran into a test problem with `plotNA_distribution`.
It returns 0 now, not the plot.

At checks, you will probably also get some NOTEs now, as no "global binding is found" for some variables that are used in the ggplot code. We might have to define them with `utils::globalVariables()`

**Comment by SteffenMoritz** [comment]
"At checks, you will probably also get some NOTEs now, as no "global binding is found" for some variables that are used in the ggplot code. We might have to define them with utils::globalVariables()"

Fixed this already ;)
// it has to do with the check() function misinterpreting things as functions

E.g. for:
gg <- ggplot2::ggplot(data = df) +
      ggplot2::geom_bar(aes(x = id, y = val, fill = label),

Check thinks id is a function that wasn't defined in global workspace.
     Doing ggplot2::geom_bar(aes(x = df$id, y = df$val, fill = df$label), instead solves this :)

**Comment by SteffenMoritz** [comment]
"There might be something to fix then, as I ran into a test problem with plotNA_distribution.
It returns 0 now, not the plot."

Would you mind checking again (after my latest update)?
For me it worked now.

**Pull request merged**
